// Vercel Node wrapper: dynamically import the built ESM Express app from dist/index.js
// and forward requests to it. This allows the compiled server bundle to be used as
// a Vercel serverless function while keeping the server implementation in ESM.

module.exports = async function handler(req, res) {
  try {
    // Import the built server entry. This file is generated by the repo build step
    // (package.json build script outputs to dist/index.js). We import dynamically
    // so the module is loaded once per function cold start and cached by the runtime.
    const mod = await import('../dist/index.js');
    const app = mod && (mod.default || mod);

    if (!app || typeof app !== 'function') {
      console.error('Imported server module did not export an Express app.');
      res.statusCode = 500;
      return res.end('Server misconfigured');
    }

    // Express apps are callable functions (req, res), so forward the request.
    return app(req, res);
  } catch (err) {
    console.error('Error loading server app:', err);
    res.statusCode = 500;
    res.end('Server error');
  }
};
